apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: petclinic-dep
  name: petclinic-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic-dep
    spec:
      containers:
      - image: petclinic:latest
        name: petclinic-image
        imagePullPolicy: Never
        ports: 
          - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ACS
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_URL
        - name: SPRING_DATASOURCE_password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ACS
        resources: {}
      
status: {}
