version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic # ?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_password: petclinic
    depends_on:
      - mysql

volumes:
  mysql_data:
  mysql_config: