apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: petclinic-dep
  name: petclinic-ns
spec:
  ports:
  - name: 8080-8080
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30012
  selector:
    app: petclinic-dep
  type: NodePort
status:
  loadBalancer: {}
